version: "3.8"

services:
  app:
    image: bibliopi:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
    ports:
      - "9090:9090"
      - "9091:9091"
    volumes:
      - data:/app/data
      - backups:/app/backups
    environment:
      - NODE_ENV=production
      - DB_TYPE=sqlite
    networks:
      - bibliopi_net

  postgres:
    image: postgres:16-alpine
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    environment:
      - POSTGRES_DB=bibliopi
      - POSTGRES_USER=bibliopi
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bibliopi_net

networks:
  bibliopi_net:
    driver: overlay

volumes:
  data:
  backups:
  postgres_data:

secrets:
  db_password:
    external: true
